language: ruby

services:
  - mysql
  - postgresql

rvm:
  - 2.3.1

cache: bundler

env:
  - REDMINE_VER=3.4.7 DB=mysql
  - REDMINE_VER=3.4.7 DB=postgresql
  - REDMINE_VER=3.4.0 DB=mysql
  - REDMINE_VER=3.4.0 DB=postgresql

before_install:
  - export PLUGIN_NAME=redmine_risks
  - export REDMINE_PATH=$HOME/redmine
  - export BUNDLE_GEMFILE=$REDMINE_PATH/Gemfile
  - svn co http://svn.redmine.org/redmine/tags/$REDMINE_VER $REDMINE_PATH
  - ln -s $TRAVIS_BUILD_DIR $REDMINE_PATH/plugins/$PLUGIN_NAME
  - cp pipeline/travis/database-$DB.yml $REDMINE_PATH/config/database.yml
  - cd $REDMINE_PATH

before_script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake redmine:plugins:migrate

script:
  - bundle exec rake redmine:plugins:test NAME=$PLUGIN_NAME RUBYOPT="-W0"
